export const MAX_TREE_SIZE_RATIO = 0.2;
export const MIN_TREE_SIZE_RATIO = 0.05;
export const TREE_LEVEL = 11;
export const LINE_WIDTH = [10, 9, 8, 7, 6, 4, 3, 2, 1, 0.5, 4];
export const ANIMATION_FRAME = 20;
export const MIN_ANGLE_DIFF = Math.PI / 12; // 15`
export const MAX_ANGLE_DIFF = Math.PI / 6; // 30`
export const FLOWER_COLORS = ["#F4A8BE", "#FFAAAA", "#FFC0C8", "#FEEEED"];
export const BRANCH_COLORS = ["#231709", "#371D10", "#352315"];
export const BACKGROUND_COLOR = "#FFFFFF";
export const CANVAS_UPPER_OFFSET = 100;
export const LINE_WIDTH_RATIO = 0.01;
